name: Mirror Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Push to Secondary Repo
        env:
          MIRROR_REPO_URL: ${{ secrets.MIRROR_REPO_URL }}
        run: |
          git remote add secondary "$MIRROR_REPO_URL"
          git push --mirror -f secondary
